### ISSUE TITLE
DELETE_AFTER env variable not working properly

### ISSUE THREAD

**Issue by danys94** [SpyrosRoum/termpad#12]
Hey sir! I have following setup
```
version: "3.4"

services:
  app:
    image: spyrosr/termpad
    ports:
      - 9999:8000
    environment:
      - DOMAIN_NAME=XX.XXX.XX/raw
      - HTTPS=true
      - DELETE_AFTER=1
    volumes:
      - data:$HOME/.local/share/termpad/
    restart: always

volumes:
  data:
    name: termpad
```
And it actually deletes in less than one hour, I was monitoring this and it was about 50 minutes. I thought `DELETE_AFTER` environment variable stands for days. 
Is there a bug? 
Thank you in advance!
