### ISSUE TITLE
Files not visible on host system when running via docker

### ISSUE THREAD

**Issue by SpyrosRoum** [SpyrosRoum/termpad#15]
@EricZimmerman reports in #10 that he can't locate the files in his system when running V2 via docker compose.

**Comment by SpyrosRoum** [comment]
@EricZimmerman hi, so far I haven't been able to reproduce this. Specifically when I use the following docker compose I can see files just fine. Can you share your whole compose? Leave out the url of course.

sample docker-compose:
```yml
services:
  app:
    build: .  # I'm running it from the repo directly, you should have the image here.
    ports:
      - 8000:8000
    environment:
      - DOMAIN_NAME=localhost
      - HTTPS=false
      - DELETE_AFTER=0 # If you are hosting for yourself keeping them forever is probably fine
      - OUTPUT=/termpad/share
    volumes:
      - /tmp/termpad:/termpad/share
    restart: always
```
In this case I can see files in `/tmp/termpad` and a log line `Using `/termpad/share `for saving files`

**Comment by EricZimmerman** [comment]
```
services:
  app:
    container_name: termpad
    image: spyrosr/termpad:v2
    ports:
      - 8990:8000
    environment:
      - DOMAIN_NAME=termpad.zyz.com
      - HTTPS=true
      - DELETE_AFTER=3
      - OUTPUT=/termpad/share
    #  - RUST_LOG=DEBUG
    volumes:
      # - data:$HOME/.local/share/termpad/
      #      - /data/termpad:/termpad/share
      # - /data/termpad:/termpad/share
      - /data/termpad:/termpad/share/
    restart: always
volumes:
  data:
    name: termpad
networks: {}
```

more or less what is [here](https://github.com/SpyrosRoum/termpad?tab=readme-ov-file#with-docker-compose)

**Comment by SpyrosRoum** [comment]
Okay, I see what's going on. You have defined a volume at the end, but you don't use it. Instead you use the path `/data/termpad`. You should be able to `cd /data/termpad` and see all the files on your host.

I'd say remove the volume section from the end completely, move the files where you want them to be, and update the volumes entry to look like this:
```yml
services:
  app:
    ...
    volumes:
       - /where/you/want/them/to/be:/termpad/share/
```

Let me know if this works

**Comment by EricZimmerman** [comment]
that  seems to have done it!

```
#https://github.com/SpyrosRoum/termpad
services:
  app:
    container_name: termpad
    image: spyrosr/termpad:v2
    ports:
      - 8990:8000
    environment:
      - DOMAIN_NAME=termpad.zyz.com
      - HTTPS=true
      - DELETE_AFTER=3
      - OUTPUT=/termpad/share
    volumes:
      - /data/termpad:/termpad/share/
    restart: always
```

it even moved the file for me on restarting. made a new one, now i see 2 files in /data/termpad. thanks!
